# Generated by Django 2.2 on 2020-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=100)),
                ('telefonos', models.CharField(max_length=20)),
            ],
        ),
    ]
